excluded:
  - GitHubActivityFeedTests
  - GitHubActivityFeedUITests
  - Resources
  - Routable/Tests
  - Architecture/Tests
  
disabled_rules:
  - trailing_whitespace
  - nesting
  - statement_position
  - colon

warning_threshold: 20

type_body_length:
  warning: 250
  error: 350
file_length:
  warning: 350
  error: 500
function_body_length:
  warning: 40
  error: 50
line_length:
  warning: 150
  error: 200
type_name:
  excluded:
    - Of
    - In
cyclomatic_complexity:
    error: 10
identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    error: 40
  excluded:
    - h1
    - h2
    - h3
    - h4
    - h5
    - id
    - of
    - in
